# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20180803_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
