# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20181116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_posts',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='pending', max_length=3),
        ),
    ]
