# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_blog_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_posts',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='pending', max_length=15),
        ),
    ]
